```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Load Packages -- used here
## ===========================================================================================================
library(readxl)
library(dplyr)
library(rstanarm)
library(broom)
library(coda)
library(ggplot2)

## ===========================================================================================================
## Set seed for reproducibility 
## ===========================================================================================================
set.seed(98024790)
seed <- c(98024790)
```

## ===========================================================
## 1. Larval hatch
## ===========================================================

```{r, warnings = FALSE, message = FALSE}
## ===========================================================
## Load data
## ===========================================================
larvae.hatch <- read_excel("/Users/Taylor/Dropbox/Cisco-Data/data/2017-Larvae-Rearing.xlsx", sheet = "hatching") %>% 
  mutate(treatment = factor(tank.id),
         time = paste0(substr(.$time, 1, 2),":",substr(.$time, 3, 4)))

larvae.hatch %<>% mutate(datetime = as.POSIXct(paste(larvae.hatch$date, larvae.hatch$time, sep = " "), format="%Y-%m-%d %H:%M"),
                         fertilization.date = as.POSIXct("2016-12-01 12:00:00"),
                         dpf = as.numeric(datetime-fertilization.date)) %>% 
  dplyr::select(date, time, datetime, fertilization.date, dpf, treatment, quantity = larvae.hatched) %>% 
  arrange(treatment, date, time, datetime) %>% group_by(treatment) %>% 
  mutate(cumsum = cumsum(quantity),
         total = sum(quantity),
         prop = cumsum/total) %>% 
  arrange(treatment, date, time, datetime)

## ===========================================================
## Simulated data
## ===========================================================
beta0 <- -50
beta1 <- 0.5
test.y <- runif(1000, min = 85, max = 110)
pVect <- exp(beta0 + beta1 * test.y) / (1 + exp(beta0 + beta1 * test.y))
range(pVect)
test.x <- rbinom(n = length(test.y), size = 1, prob = pVect)
```

```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Define negative log likelihood function
## ===========================================================================================================
nllBinom <- function(parVec, hatch, dpf, total){
    b0 <- parVec[1]
    b1 <- parVec[2]
  pVect <- exp(b0 + b1 * dpf) / (1 + exp(b0 + b1 * dpf))
  nllik <- -sum(dbinom(x = hatch, size = total, prob = pVect, log = TRUE))
  return(nllik)
}

## ===========================================================================================================
## Create data frames for each treatment
## ===========================================================================================================
trt.hatch.a <- larvae.hatch %>% filter(treatment == "A")
trt.hatch.b <- larvae.hatch %>% filter(treatment == "B")
trt.hatch.c <- larvae.hatch %>% filter(treatment == "C")


## ===========================================================================================================
## Optimize likelihood functions
## ===========================================================================================================
#outBinom.test <- optim(par = c(-50.0, 0.50), fn = nllBinom, hatch = test.x, dpf = test.y, total = 1)
outBinom.a <- optim(par = c(-50.0, 0.50), fn = nllBinom, hatch = trt.hatch.a$cumsum, dpf = trt.hatch.a$dpf,
                    total = trt.hatch.a$total)
outBinom.b <- optim(par = c(-50.0, 0.50), fn = nllBinom, hatch = trt.hatch.b$cumsum, dpf = trt.hatch.b$dpf,
                    total = trt.hatch.b$total)
outBinom.c <- optim(par = c(-50.0, 0.50), fn = nllBinom, hatch = trt.hatch.c$cumsum, dpf = trt.hatch.c$dpf,
                    total = trt.hatch.c$total)


## ===========================================================================================================
## Calculate days-post-fertilization at 50% hatching
## ===========================================================================================================
(xA <- as.numeric((log(0.5 / (1-0.5)) - outBinom.a$par[1]) / outBinom.a$par[2]))
(xB <- as.numeric((log(0.5 / (1-0.5)) - outBinom.b$par[1]) / outBinom.b$par[2]))
(xC <- as.numeric((log(0.5 / (1-0.5)) - outBinom.c$par[1]) / outBinom.c$par[2]))
```


```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Create fitted data using parameter estimates
## ===========================================================================================================
yPred.a <- data.frame(treatment = "A",
                      y = exp(outBinom.a$par[1] + outBinom.a$par[2] * seq(89, 114, length.out = 500)) / (1 + exp(outBinom.a$par[1] + outBinom.a$par[2] * seq(89, 114, length.out = 500))),
                    x = seq(89, 114, length.out = 500))
yPred.b <- data.frame(treatment = "B",
                      y = exp(outBinom.b$par[1] + outBinom.b$par[2] * seq(89, 114, length.out = 500)) / (1 + exp(outBinom.b$par[1] + outBinom.b$par[2] * seq(89, 114, length.out = 500))),
                    x = seq(89, 114, length.out = 500))
yPred.c <- data.frame(treatment = "C",
                      y = exp(outBinom.c$par[1] + outBinom.c$par[2] * seq(89, 114, length.out = 500)) / (1 + exp(outBinom.c$par[1] + outBinom.c$par[2] * seq(89, 114, length.out = 500))),
                    x = seq(89, 114, length.out = 500))

yPred <- rbind(yPred.a, yPred.b, yPred.c)

## ===========================================================================================================
## Plot
## ===========================================================================================================
ggplot(larvae.hatch, aes(x = dpf, y = prop, color = treatment)) + 
  geom_point(size = 5) + 
  geom_path(data = yPred, aes(x = x, y = y, color = treatment), size = 2) + 
  geom_segment(aes(x = xA, y = -0.015, xend = xA, yend = 0.5), colour = "#8fccf0", size = 0.65) + 
  geom_segment(aes(x = xB, y = -0.015, xend = xB, yend = 0.5), colour = "#0071b3", size = 0.65) + 
  geom_segment(aes(x = xC, y = -0.015, xend = xC, yend = 0.5), colour = "#4d4d4d", size = 0.65) + 
  geom_hline(yintercept = 0.50, colour = "#4d4d4d", size = 0.65) + 
  scale_x_continuous(limits = c(89, 114), breaks = seq(90, 115, 5), expand = c(0,0)) +
  scale_y_continuous(limits = c(-0.015, 1.015), expand = c(0, 0)) +
  scale_color_manual(values = c("#8fccf0", "#0071b3", "#4d4d4d"), labels = c("Continuous Light", "Photoperiod Light", "No Light")) +
  labs(x = "\nDays Post-fertilization (DPF)", y = "Proportion of Hatched Larvae\n") +
  theme(panel.background = element_blank(), panel.grid = element_blank(), 
        axis.line = element_line(), axis.text = element_text(size = 27),
        axis.title = element_text(size = 35), axis.ticks.length = unit(2, 'mm'),
        legend.position = c(0.165,0.9), legend.text = element_text(size = 30),
        legend.title = element_blank(), legend.key.size = unit(2, 'lines'),
        legend.key.width = unit(5, 'lines'), legend.key.height = unit(2, 'lines'),
        legend.key = element_blank(), plot.margin = unit(c(5, 5, 5, 5), "mm"))

ggsave("/Users/Taylor/Dropbox/Cisco-Data/figures/2017-hatching-logistic-regression-bayesian.png", dpi = 600, width = 18.5, height = 10)
```




## ===========================================================================================================
## 2. Yolk-sac area
## ===========================================================================================================

```{r, warnings = FALSE, message = FALSE} 
## ===========================================================================================================
## Load data
## ===========================================================================================================
larvae.yolk <- read_excel("/Users/Taylor/Dropbox/Cisco-Data/data/2017-Development-Growth.xlsx", sheet = "Larvae Hatch") %>% 
  mutate(Treatment = factor(Treatment),
         Date = factor(gsub("-", "", .$Date))) %>% 
  filter(Yolk.Area.mm2 != 0,
         Include.Yolk == "Y") %>% 
  dplyr::select(date = Date, treatment = Treatment, yolk.area = Yolk.Area.mm2)
```

```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Fit stan model
## ===========================================================================================================
outRstan.yolk <- stan_glm(yolk.area ~ treatment, data = larvae.yolk, iter = 10000, warmup = 1000,
                          chains = 4, prior_intercept = normal(0, 100), prior = normal(0, 100), 
                          prior_aux = cauchy(0, 2), seed = seed)

## ===========================================================================================================
## MCMC diagnostics
## ===========================================================================================================
plot(outRstan.yolk, "trace", pars = c("(Intercept)", "treatmentB", "treatmentC"),
     facet_args = list(nrow = 3))
plot(outRstan.yolk, "acf", pars = c("(Intercept)", "treatmentB", "treatmentC"))

## ===========================================================================================================
## Calculate HOD intervals
## ===========================================================================================================
hpd.yolk <- tidyMCMC(outRstan.yolk, conf.int = TRUE, conf.method = "HPDinterval") %>% 
  rename(treatment = term) %>% 
  filter(treatment %in% c("(Intercept)", "treatmentB", "treatmentC"))
hpd.yolk$treatment <- c("A", "B", "C")
hpd.yolk[2, 2] <- hpd.yolk[2, 2] + hpd.yolk[1, 2]
hpd.yolk[3, 2] <- hpd.yolk[3, 2] + hpd.yolk[1, 2]
hpd.yolk[2, 4] <- hpd.yolk[2, 4] + hpd.yolk[1, 4]
hpd.yolk[3, 4] <- hpd.yolk[3, 4] + hpd.yolk[1, 4]
hpd.yolk[2, 5] <- hpd.yolk[2, 5] + hpd.yolk[1, 5]
hpd.yolk[3, 5] <- hpd.yolk[3, 5] + hpd.yolk[1, 5]
hpd.yolk$group <- c("a", "b", "b")
```

```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Plot
## ===========================================================================================================
ggplot(data = hpd.yolk, aes(x = treatment, y = estimate)) +
  geom_point(size = 4.5) + 
  geom_text(aes(label = group), hjust = -1.0, vjust = 0.35, size = 9, colour = "black") + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.25, size = 1.5) +
  scale_y_continuous(limits = c(0.65, 1.1), breaks = seq(0.65, 1.1, 0.05), expand = c(0, 0)) +
  scale_x_discrete(labels = c("Continuous Light", "Photoperiod Light", "No Light")) +
  labs(y = expression("Mean Yolk-sac Area"~(mm^2)), x = '') +
  theme(panel.background = element_blank(), panel.grid = element_blank(), 
        axis.line = element_line(), axis.text.y = element_text(size = 25, colour = "black"),
        axis.text.x = element_text(size = 23, colour = "black"),
        axis.ticks.length = unit(2, 'mm'), axis.title.y = element_text(size = 30),
        legend.position = c(0.145,0.9), legend.text = element_text(size = 25),
        legend.title = element_blank(), legend.key.size = unit(2, 'lines'),
        legend.key.width = unit(5, 'lines'), legend.key.height = unit(2, 'lines'),
        plot.margin = unit(c(5, 13, 5, 5), "mm"), text = element_text(family = 'Helvetica'))

ggsave("/Users/Taylor/Dropbox/Cisco-Data/figures/2017-yolk-sac-area-trt-bayesian.png", dpi = 600, width = 11, height = 9)
```




## ===========================================================================================================
## 3. Length-at-Hatch
## ===========================================================================================================

```{r}
## ===========================================================================================================
## Load data
## ===========================================================================================================
larvae.tl.hatch <- read_excel("/Users/Taylor/Dropbox/Cisco-Data/data/2017-Development-Growth.xlsx", sheet = "Larvae Hatch") %>% 
  mutate(Treatment = factor(Treatment)) %>% 
  filter(TL.mm != 0,
         Include.TL == "Y") %>% 
  dplyr::select(date = Date, treatment = Treatment, tl.mm = TL.mm)
```

```{r}
## ===========================================================================================================
## Fit stan model
## ===========================================================================================================
outRstan.tl <- stan_glm(tl.mm ~ treatment, data = larvae.tl.hatch, iter = 10000, warmup = 1000,
                        chains = 4, prior_intercept = normal(0, 100), prior = normal(0, 100), 
                        prior_aux = cauchy(0, 2), seed = seed)

## ===========================================================================================================
## MCMC diagnostics
## ===========================================================================================================
plot(outRstan.tl, "trace", pars = c("(Intercept)", "treatmentB", "treatmentC"),
     facet_args = list(nrow = 3))
plot(outRstan.tl, "acf", pars = c("(Intercept)", "treatmentB", "treatmentC"))

## ===========================================================================================================
## Calculate HPD intervals
## ===========================================================================================================
hpd.tl <- tidyMCMC(outRstan.tl, conf.int = TRUE, conf.method = "HPDinterval") %>% 
  rename(treatment = term) %>% 
  filter(treatment %in% c("(Intercept)", "treatmentB", "treatmentC"))
hpd.tl$treatment <- c("A", "B", "C")
hpd.tl[2, 2] <- hpd.tl[2, 2] + hpd.tl[1, 2]
hpd.tl[3, 2] <- hpd.tl[3, 2] + hpd.tl[1, 2]
hpd.tl[2, 4] <- hpd.tl[2, 4] + hpd.tl[1, 4]
hpd.tl[3, 4] <- hpd.tl[3, 4] + hpd.tl[1, 4]
hpd.tl[2, 5] <- hpd.tl[2, 5] + hpd.tl[1, 5]
hpd.tl[3, 5] <- hpd.tl[3, 5] + hpd.tl[1, 5]
hpd.tl$group <- c("a", "a", "a")
```

```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Plot
## ===========================================================================================================
ggplot(data = hpd.tl, aes(x = treatment, y = estimate)) +
  geom_point(size = 4.5) + 
  geom_text(aes(label = group), hjust = -1.0, vjust = 0.35, size = 9, colour = "black") + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.25, size = 1.5) +
  scale_y_continuous(limits = c(10.25, 11.25), breaks = seq(10.25, 11.25, 0.25), expand = c(0, 0)) +
  scale_x_discrete(labels = c("Continuous Light", "Photoperiod Light", "No Light")) +
  labs(y = "Mean Length-at-Hatch (mm)", x = '') +
  theme(panel.background = element_blank(), panel.grid = element_blank(), 
        axis.line = element_line(), axis.text.y = element_text(size = 25, colour = "black"),
        axis.text.x = element_text(size = 23, colour = "black"),
        axis.ticks.length = unit(2, 'mm'), axis.title.y = element_text(size = 30),
        legend.position = c(0.145,0.9), legend.text = element_text(size = 25),
        legend.title = element_blank(), legend.key.size = unit(2, 'lines'),
        legend.key.width = unit(5, 'lines'), legend.key.height = unit(2, 'lines'),
        plot.margin = unit(c(5, 13, 5, 5), "mm"), text = element_text(family = 'Helvetica'))

ggsave("/Users/Taylor/Dropbox/Cisco-Data/figures/2017-LAH-trt-bayesian.png", dpi = 600, width = 11, height = 9)
```


## ===========================================================================================================
## 4. Larval growth
## ===========================================================================================================

```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Load data
## ===========================================================================================================
larvae.tl.growth <- read_excel("/Users/Taylor/Dropbox/Cisco-Data/data/2017-Development-Growth.xlsx", sheet = "Larvae Growth") %>% 
  mutate(Treatment = factor(Treatment),
         Date = as.factor(Date)) %>% 
  filter(TL.mm != 0,
         Include.TL == "Y") %>% 
  dplyr::select(date = Date, treatment = Treatment, tl.mm = TL.mm) %>% 
  mutate(date = as.Date(date),
         start.date = as.Date(ifelse(.$treatment == "A", "2017-03-11",
                                     ifelse(.$treatment == "B", "2017-03-17",
                                            ifelse(.$treatment == "C", "2017-03-16", NA)))))

larvae.tl.hatch <- read_excel("/Users/Taylor/Dropbox/Cisco-Data/data/2017-Development-Growth.xlsx", sheet = "Larvae Hatch") %>% 
  mutate(Treatment = factor(Treatment)) %>% 
  filter(TL.mm != 0,
         Include.TL == "Y") %>% 
  dplyr::select(date = Date, treatment = Treatment, tl.mm = TL.mm) %>% 
  mutate(date = as.Date(ifelse(.$treatment == "A", "2017-03-11",
                               ifelse(.$treatment == "B", "2017-03-17",
                                      ifelse(.$treatment == "C", "2017-03-16", NA)))),
         start.date = as.Date(ifelse(.$treatment == "A", "2017-03-11",
                                     ifelse(.$treatment == "B", "2017-03-17",
                                            ifelse(.$treatment == "C", "2017-03-16", NA)))))

larvae.tl <- bind_rows(larvae.tl.hatch, larvae.tl.growth) %>% 
  mutate(dph = as.numeric(date - start.date)) %>% 
  dplyr::select(treatment, tl.mm, dph)

## ===========================================================
## Simulated data
## ===========================================================
beta0 <- 10.0
beta1 <- 0.05
test.x <- runif(100, min = 0, max = 85)
test.y <- beta0 + (beta1 * test.x)
test.growth <- data.frame(y = test.y, x = test.x)
```

```{r, warnings = FALSE, message = FALSE}
## ===========================================================================================================
## Create data frames for each treatment
## ===========================================================================================================
trt.growth.a <- larvae.tl %>% filter(treatment == "A")
trt.growth.b <- larvae.tl %>% filter(treatment == "B")
trt.growth.c <- larvae.tl %>% filter(treatment == "C")

## ===========================================================================================================
## Fit Stan models
## ===========================================================================================================
outRstan.growth.a <- stan_glm(tl.mm ~ dph, data = trt.growth.a, iter = 10000, warmup = 1000,
                       chains = 4, prior_intercept = normal(0, 100),
                       prior = normal(0, 100), prior_aux = cauchy(0, 2), seed = seed)
outRstan.growth.b <- stan_glm(tl.mm ~ dph, data = trt.growth.b, iter = 10000, warmup = 1000,
                       chains = 4, prior_intercept = normal(0, 100),
                       prior = normal(0, 100), prior_aux = cauchy(0, 2), seed = seed)
outRstan.growth.c <- stan_glm(tl.mm ~ dph, data = trt.growth.c, iter = 10000, warmup = 1000,
                       chains = 4, prior_intercept = normal(0, 100),
                       prior = normal(0, 100), prior_aux = cauchy(0, 2), seed = seed)

## ===========================================================================================================
## MCMC diagnostics
## ===========================================================================================================
plot(outRstan.growth.a, "trace", pars = c("(Intercept)", "dph"),
     facet_args = list(nrow = 2))
plot(outRstan.growth.a, "acf", pars = c("(Intercept)", "dph"))

plot(outRstan.growth.b, "trace", pars = c("(Intercept)", "dph"),
     facet_args = list(nrow = 2))
plot(outRstan.growth.b, "acf", pars = c("(Intercept)", "dph"))

plot(outRstan.growth.c, "trace", pars = c("(Intercept)", "dph"),
     facet_args = list(nrow = 2))
plot(outRstan.growth.c, "acf", pars = c("(Intercept)", "dph"))

## ===========================================================================================================
## Parameter summaries
## ===========================================================================================================
hpd.growth.a <- tidyMCMC(outRstan.growth.a, conf.int = TRUE, conf.level = 0.95, conf.method = "HPDinterval")
hpd.growth.b <- tidyMCMC(outRstan.growth.b, conf.int = TRUE, conf.method = "HPDinterval")
hpd.growth.c <- tidyMCMC(outRstan.growth.c, conf.int = TRUE, conf.method = "HPDinterval")
```

```{r}
## ===========================================================================================================
## Create fitted data from parameter estimates
## ===========================================================================================================
yPred.a <- data.frame(treatment = "A",
                      y = (outRstan.a$coefficients[1] + outRstan.a$coefficients[2] * seq(0, 81, length.out = 500)),
                      x = seq(0, 81, length.out = 500))
yPred.b <- data.frame(treatment = "B",
                      y = (outRstan.b$coefficients[1] + outRstan.b$coefficients[2] * seq(0, 81, length.out = 500)),
                      x = seq(0, 81, length.out = 500))
yPred.c <- data.frame(treatment = "C",
                      y = (outRstan.c$coefficients[1] + outRstan.c$coefficients[2] * seq(0, 81, length.out = 500)),
                      x = seq(0, 81, length.out = 500))
yPred <- rbind(yPred.a, yPred.b, yPred.c)

## ===========================================================================================================
## Plot
## ===========================================================================================================
ggplot(larvae.tl, aes(x = dph, y = tl.mm, colour = treatment)) +
  geom_point(size = 3) +
  geom_path(data = yPred, aes(x = x, y = y, colour = treatment), size = 1.5) +
  scale_x_continuous(limits = c(0, 81), breaks = seq(0, 80, 20), expand = c(0.01, 0.01)) +
  scale_y_continuous(limits = c(8.5, 20), breaks = seq(10, 20, 2), expand = c(0, 0)) +
  scale_color_manual(values = c("#8fccf0", "#0071b3", "#4d4d4d"), 
                     labels = c("Continuous Light", "Photoperiod Light", "No Light")) +
  labs(x = "\nDays Post-hatching (DPH)", y = "Total Length (mm)\n") +
  theme(panel.background = element_blank(), panel.grid = element_blank(), 
        axis.line = element_line(), axis.text = element_text(size = 22),
        axis.title = element_text(size = 28), axis.ticks.length = unit(2, 'mm'),
        legend.position = c(0.205, 0.88), legend.text = element_text(size = 24),
        legend.title = element_blank(), legend.key.size = unit(1, 'lines'),
        legend.key.width = unit(3, 'lines'), legend.key.height = unit(2, 'lines'),
        legend.key = element_blank(), text = element_text(family = 'Helvetica'),
        plot.margin = unit(c(5, 4, 5, 5), "mm"))

ggsave("/Users/Taylor/Dropbox/Cisco-Data/figures/2017-larvae-growth-bayesian.png", dpi = 600, width = 14, height = 8)
```
