---
title: 'Bayesian GLM: Binomial'
output:
  html_document:
    df_print: paged
---

Binomial / logistic regression

```{r}
library(rethinking)
data("Panda_nuts")
d<-Panda_nuts
d$helpN<-as.numeric(d$help)-1
plot(helpN~age, data=d)
```

```{r}
out<-glm(helpN~age,family=binomial(link = "logit"),data=d)
summary(out)

plot(helpN~age, data=d)
curve((exp(out$coefficients[1] + out$coefficients[2]*x) / (1+exp(out$coefficients[1] + out$coefficients[2]*x))),add=TRUE)
```

```{r}

d_trim <- list(help=d$helpN,A=d$age)
  
nutCracking_stan <- ulam(
    alist(
        help ~ dbinom(1,p),
        logit(p) <- intercept + bA * A,
        intercept ~ dnorm(0,1.5),
        bA ~ dnorm(0,1.5)
    ) , data = d_trim ,chains=4, log_lik=TRUE, iter=10000 )

precis(nutCracking_stan)


```

```{r}
d_trim <- list(help=d$helpN,A=d$age)
  
nutCracking_stanPrior2 <- ulam(
    alist(
        help ~ dbinom(1,p),
        logit(p) <- intercept + bA * A,
        intercept ~ dnorm(0,10),
        bA ~ dnorm(0,10)
    ) , data = d_trim, chains=4, log_lik=TRUE, iter=10000  )

precis(nutCracking_stanPrior2)
```


Fitting the binomial regression using our own likelihood function

```{r}
nllBinomReg<-function(parVec,data=d){
  help<-data$helpN
  age<-data$age
  intercept<-parVec[1]
  beta<-parVec[2]
  p<-exp(intercept + beta*age) / (1 + exp(intercept + beta*age) )
  nllik<- -sum(dbinom(x=help,size=1, prob=p,log=TRUE))
  return(nllik)
}
```


```{r}
parVec<-c(1.0,0.5)
out<-optim(par=parVec,fn=nllBinomReg,method="L-BFGS-B",
               lower=c(-Inf,-Inf),upper=c(Inf,Inf))
AIC<- 2*out$value + 2*2

out$par
AIC
```
```{r}
nllBinomReg(out$par)
out$value
```







